module.exports = {
  'BE-CC2': `In the BE-CC2 case study, several innovations have been considered. The first innovations imply new practices such as Fast rotational grazing, the use of catch crop as winter feed and a combination of both. A complete re-design of such cow-calf system into a fattener unit of cross-bred males coming from dairy units has also been considered.

According to the model, FRG is applied on more than 17 ha (over the xx of permanent grassland). The impact of FRG is double: it allows to produce more grass and increase the production of these plots. While the quality increase allows to reduce the quantity of supplementation on pasture, the increase in quantity allows to reduce the grazed surface and produce more grass silage. It therefore indirectly reduce the use of maize silage and/or concentrate during winter feeding. The result shows a small profit change (lower than 1%), and a small but negative impact on GHG emission per kg of carcass produced, meaning that the fertilisation needed to increase the yield (from 8 to 8.8 tDM per ha) imply more GHG than the feed production, this statement requires more investigation, in particular the impact of legumes on the fertilisation is not yet taken into account. In terms of efficiency, a substancial increase of 24.3%/138.5% is observed on the net energy/protein efficiency, allowing the farm to reach a net protein efficiency of 2.

In the Catch crop scenario, the model consider the possibility to have Catch crop in the rotation before the Maize and sugarbeet, representing 18.1 ha. In practice, the assumed rotation would be WinterWheat -> WinterWheat -> Catch Crop -> Maize silage -> ... . The main implication we found are the production of high quality silage for winter use, reducing therefore the use of concentrates and increasing by 400% the protein efficiency. This result shows the interest of the innovation in system combining crops and livestock but need to be refined at the crop level. In particular, an in depth work on crops rotations and required fertilization as function of the considered rotations are mandatory to produce more reliable results.

Combining both innovations seems to indicate that both innovations can be combined to increase further the system efficiency.`,
'BE-BF': `The list of innovation tested on walloon breeder-fattener case study include Fast rotational grazing for the all herd, the use of algae, the extension of the bulls cull age (from 20m to 23m) and the herd size reduction.
As in the baseline, the use of sugar beet pulp is important in these optimisation results. While the results are realistic, the amount of sugar beet pulp varies a lot among the breeder and the impact of innovations may vary accordingly.

The fast rotational grazing scenario implies the mother cows, the bulls and the heeifers to be out from May to september included. More than 34 ha out of the 48 ha of permanent grasslands are converted into a paddock system. The animals are supplemented on pasture with moist beet pulp when needed, months with low yield or for mother cows.
While the growing phase is possible on "full grazing", the fattening phase (2 months from 560 kg to 640 kg live weight) is performed with a ~3 kg of sugar beet pulp supplementation on pasture.
This innovations improve most of the indicators: Profit by 3%, protein efficiency by 7%, and calory efficiency by 1%. The global warming potential is not impacted (-0.25%), and further studies are needed to explore the modification in the methane emissions comming from a grass+pulp compared to a more classical indoor feeding.

Since the price of algae in the future is uncertain, we have tested prices of algae ranging from 1 to 8000 Euros.
Above 500 euros, buying Chlorella is not considered in the model. 49 ton are bought if the price reach 200 euros/ton and increase further for lower prices (239 tons at 100 euros/t).
If one consider the use of an algae with similar characteristics as chlorella and not competitive feed, the impact on the protein efficiency is important and increases by 7 to 96% for 200 euros and 100 euros respectively.
On the other hand, the impact on the climate change is important: an extra 12 to 68% for the same prices hypthesis.

Increasing the cull age of bulls is often tought as being a good option to increase the net efficiency of a breeder-fattener system.
Indeed, a lower daily weight gain would allow to produce meat by using less high proteic/energetic feed and therefore probably more grass, increasing therefore the net efficiency.
It is not what we observe in this case, where we increased the cull age and kept the number of cows fixed at 115 Mother cows. This case study being relatively intensive (in the sense that it uses own cereal and buys 959 t of moist beet pulp), when forcing the bulls to eat more (3months extra) to produce the same amount of meat, we observe a reduction of the net efficiency. Indeed, the amount of grass per year being constant, the more grass is given to the bulls, the less grass is given to the mothercows during winter for instance. Other economic and environmental indicators are also negative.

Probably the most extreme way to reduce the competition between feed and food is to reduce the herd size. While the baseline farm had 115 cows, we forced a reducedion of this number to 100, 85, 70 and 55.
The results show as expected an increase in protein and energy efficiency that increase. In particular the protein efficiency reach more than 2 in the 70 cows case (106 LU for 48 ha of grassland).
The profit and the climate impact per kg of meat produced are badly impacted (-19% of profit and +9.4% in GWP).`,
'BE-D': `The innovations tested were related to the meat production from the male calves produced in dairy systems. In this case, cross-breeding and the possibility to use sexed semen (female dairy and male BB).
Since we look anly at a part of the complete system, one could just have a look at the profit changes coming from these innovations.


In one hand, cross-breeding allows to increase the calves revenue thanks to the higher price of cross breds. On the other hand, it potentially increases the quantity of artificial insemination and therefore increase the number of unproductive months. In this case, the profit increase by 3.8%.

When allowing to use sexing, the profit increase further to 6.3% by keeping only the number of female calves needed for replacement, all other calves are BB cross-bred sold.`,
'BE-CC1': `Since the net efficiency of the baseline is already around 2 for this extensive farm (the model results are that a grass only based diet is an economic optimum at such low LU/ha), the considered innovations were mainly focused on the increase of the output: FRG and changing the farm to a breeder-fattener system.

These innovations increase the profit of 11 and 21%, and reduced the climate impact per kg of meat produced from 3.5 and 16%.
In the breeder fattener system, 43 t of sugar beet pulp was bought to complement the grass based diet, keeping the amount of feed edible by human negligible.`,
  'Fr.Cant-CC': 'In the scenario Fr.Cant.CC tested innovations included crossbreeding of Saler and Angus, fast rotational grazing and male and female sexing. The crossbred animals have a higher weight gain. The higher intensity leads to a lower conversion efficiency of feed to food (protein and calories) as the amount of concentrates in the ration increases slightly. The high yielding animals increase the farms profits and reduce GHG emissions per kg live weight output. WE conclude that there is a trade-off between feed/food competition and profit and GWP in the case of higher yielding animals. If combined with the usage of sexed semen the effect is further increased as more, heavier male calves are born. However, the usage of sexed semen depends on the genomic potential of the bull: lower yielding Saler sperm is less profitable as higher yielding Angus bulls. Fast rotational grazing was adopted if alongside with a higher yield the nutrient composition of the grass is improved, too. If adopted, FRG is able to improve profits, GWP and calorie and protein efficiency. This is due to the replacement of concentrates in the feed with the nutrient rich FRG.',
  'FR.Cant-DCC': 'Fr.Cant.DCC is a mixed farm with a dairy herd and mother cow herd that produces weanlings. The mothercow herd is used to valorize marginal grasslands and pastures that are too poor for dairy production. WE tested the impact of two fast rotational grazing scenarios: one with higher yield and one with higher yield and better nutrient composition in the grass. If only the yield is increased the innovation is not adopted. Short-term the farm endowment in stable places is not increasing so the herd size cannot be increased hence the additional yield cannot be utilized. If the nutrient density in the yield is increased, the amount of concentrates in the ration can be reduced. This leads to savings in GHG, higher profit and improved calorie and protein efficiency.',
  'Fr.Lim-CC': 'In Lim_CC three innovations have been tested: cross breeding, fast rotational grazing and the usage of sexed semen. Furhtermore, combinations of the different innovations where tested, too. The cross bred animals are combinations of Limousin and smaller Angus. The innovation of cross breeding was only adopted if there was a premium on the sold animals. In this case profits were increased and GHG emissions reduced. The calorie and protein conversion efficiency from feed to food of the cross bred animals where lower compared to the pure bred limousine. They need more fodder to reach the same output level as the limousine. The impact of fast rotational grazing on the indicators depends on the made assumptions regarding the nutrient compositions of the output: If the yield is increased by 10% with same nutrient composition as in normal grazing profit, calorie and protein efficiency are increased due to the replacement of bought feedstuff with the additional grazing output. GWP is increased as the additional yield is accomplished by additional fertilizer effort. If the nutrient composition of the fast rotational grazing is assumed to be improved compared to normal grazing, this effect is outweighed by the saved concentrates. If the aforementioned Angus-Limousin cross animals are combined with fast rotational grazing GWP is further decreased as the angus breed is especially well suited to utilize grasslands. If the farm has the possibility to use sexed semen the production focus of the farm is shifted to the production of quality heifer meat. This is quite profitable as the case study farm takes part in a quality heifer sheme with premiums on fattened heifers. The farm uses the sexing technology to only produce females. If there is angus sperm and a higher price for cross animals male sexed semen is used to produce male angus cross animals and pure bred heifers. Sexing leads to increases in profit and GWP per kg live weight as well as calorie efficiency, because the total live weight output is increased. However, if the total valuechain of the male weanlings sold is considered (including fattening), this ranking might change. This indicates the need for further research of the whole production chain.',
  'Fr.Lor-BF': 'In Lor BF 3Innovations have been tested: Fast rotational grazing, Angus crossing and the usage chlorella algae for feed. For fast rotational grazing the impact follows the trends of the oterh scenarios. If only the yield is increased profit, calorie- and protein efficiency are improved while GWP is increased. This is due the replacement of concentrates in the feed stuff and a higher fertilizer demand due to the additional yield. If the nutrient content is increased, too, the replacement of concentrates outweighs the additional demand for fertilizer leading to an overall positive effect on all impact categories. Cross breeding with Angus leads to smaller animals with a lower weigh gain potential. With no premium on the cross bred animals pure bred Charolais are more profitable. With a preme cross breeding is adopted and the profit rises. The cross breds are better suited to sustain themselves with roughages and hence need less concentrates which leads to higher protein and calorie efficiency. THe GWP per kg beef meat is reduced as the overall reduction in intensity leads to a lower output. If crossbreds are raised using the FRG the gains in protein and calorie efficiency can be further improved while the higher GWP can be reversed. Algae are adopted at a price of 500€. As they are rich in nutrients they are used to replace costly concentrates. This leads to improvements in all impact categories. If the price of the algae is further reduced the farm starts to replace its roughage with algae, too. Although this leads to further improvements in profit, calorie and protein efficiency the GWP increases as the production of algae has a higher carbon footprint as maize- or grass silage. This effect is limited because we assumed a maximum of 10% of algae in the total ration due to nutritional constraints.',
  'GE.BAV-F': 'In GE BAv three innovations have been tested: Algae, fattening of Holstein X BelgiumBlue cross animals, and the usage of catch crops as feed. The algae scenario follows the same trend as in the Lor-Bf scenario: starting with a high price algae is used to replace concentrates in the feed leading to overall positive impacts on the indicators. If prices are getting lower algae is used to replace roughages (maize silage) leading to a further improvement of profit calorie and protein efficiency but an increase in GHG emissions. However, the algae innovation is only adopted at a lower price compared to Lor.Bf (~400€/t compared to 500€/t) indicating the higher opportunity costs of the baseline feed rations. The fattening of Holstein X BelgiumBlue cross animals leads to improvements in all indicators. The animals have a higher weight gain meaning they reach their final weight at a lower age. This transfer in a lower demand for feed. As the feeding regime in the baseline is already quite intensive (high share of concentrates) this translates into a net saving of feedstuff. However, the sold animals are further fattened on other farms. The environmental, social and economic performance of the final product (beef meat) is therefore questionable. The usage of catch crops for feed leads to better scores for profit and protein and calorie efficiency as the additional arable output is used to replace other feedstuff. However, the additional harvest requires additional fertilizer input which increases the emissions of GHG. The adoption of catch crops in this case study is limited due to the high share of maize silage in the crop rotation. Maize silage is harvested late in the season and therefore it is not possible to plant catch crop after silage maize.',
  'GE.LS-F': 'In GE LS the same innovations as in GE Bav are tested. Algae is used to replace other feed stuff starting at a price of Algae of ~350€/t. Due to the replacement the farm increases its profit and calorie and protein efficiency. THe GWP is increased as the replaced feedstuff had a better carbon footprint compared to the algae. For the cross bred animals we assumed a higher weight gain in the last fattening stage. The higher intensity in fattening improves the GWP and profits. The protein and calorie efficiency is decreased because to reach a higher fattening performance the feedstuff has to have a higher protein and energy content, too, meaning that more human consumable high-quality protein and calorie has to be fat. The usage of catch crops as feedstuff improves all impact categories indicating that the impact of additional fertilizer is outweighed by the replaced feedstuff.',
  'GE.NRW-DF': 'IN GE-NRW tested innovations where a combination of crossbreeding and sexing, the growing of catchcrops for feed, and fast rotational grazing. For the cross bred animals we assumed a higher weight gain in the last fattening stage. The higher intensity in fattening improves the GWP and profits. The protein and calorie efficiency is decreased because to reach a higher fattening performance the feedstuff has to have a higher protein and energy content, too, meaning that more human consumable high-quality protein and calorie has to be fat. This effect is increased as only the heavier males are raised due to the usage of male sexed semen. The usage of catch crops as feedstuff improves all impact categories indicating that the impact of additional fertilizer is outweighed by the replaced feedstuff. Fast rotational grazing is only adopted if along with the yield the nutrient density is increased, too. A simple yield increase will not lead to an adoption of the practice. The alternative usage of the grassland would be higher yielding silage which makes FRG without improvements in nutrient density obsolete. If there is a higher nutrient density in the grazed pasture the farm is able to reduce the amount of soy bean meal in the feed ration. However, as grazed pastures have a lower overall output compared to cut grassland the farm has to compensate by growing more silage maize on its arable land and buying other energy feed. The adoption of fast rotational grazing increases profit and improves GWP but the protein and calorie efficiency are slightly reduced due to the shift to maize silage instead of grass silage.',
  'IE-BMW.CC': 'In Ireland cross breeding and fast rotational grazing are already applied by practitioners. In the case study farm at hand both practices are already used in the baseline. We conclude from prior TEasgasc programs that there is still a considerable yield gap that farmers in Ireland can close through improvements in grassland management. The considered scenarios are therefore 10% additional yield and 10% additional yield with higher nutrient density on grazed pastures. Furthermore, we introduce the possibility to use sexed semen with different prices. The first grazing scenario with higher yield results in higher profit and higher GHG emissions. Profits are increased because the amount of grass silage in the ration is reduced. Production of silage requires machinery and is therefore costly. GHg emissions rise due to a greater amount of fertilizer used to obtain the higher yield. If nutrient density in the grazed grass is higher, too, the savings in silage production and therefore in diesel outweighs the effect of additional fertilizer and the overall effect is positive on GWP and profit. Calorie and protein efficiency are not effected as already in the baseline no potentially human consumable crops and products are used. The farm buys all heifers for replacement so the sexed semen can only be used to predefine the gender of the sold weanlings. The technology is adopted at a price ~12€ per cow. Before the price difference between the male and female weanlings is too small for the innovation to be profitable. If it is adopted only male weanlings are produced. Profit and GWP are increased. The male weanlings are heavier/ have a higher weight gain and therefore higher demand for fodder. In order to sustain and fatten only males the farm has to buy additional concentrates that bare carbon emissions and could be potentially be consumed by humans. Therefore protein and calorie efficiency are decreased. Again the sexing technology could still be a viable innovation to reduce feed/food competition and reduce the environmental burden of production but then the technology has to be researched in the context of the whole beef sector.',
  'IE-SE.FF': 'In IE-SE the same assumptions regarding FRG are made as in IE-BMW are made: one scenario with 10% more yield and one with 10% more yield and a higher nutrient density in the grazed grass. Both scenarios lead to improvements in all impact categories, however in the second scenario the improvement is greater. Through the additional yield silage and concentrates in the ration of the animals are replaced. Furthermore diesel is saved as silage harvest is reduced. However more fertilizer is used to obtain the higher yield. Besides FRG the fattening of Holstein and Holstein-cross animals from dairy herds on pastures with different fattening strategies and slaughter ages are tested. Compared to the baseline all indicators worsen in the Holstein scenarios. The dairy breed bulls have a lower weight gain potential and a lower end weight and hence a lower overall efficiency compared to beef breeds. In terms of profit, GWP, and calorie and protein efficiency younger sloughter ages seem to outperform longer once. In the scenarios with higher slaughter ages, the feeding efforts to just sustain the animals are summing up leading to the bad indicator scores. Further research should consider the whole production chain including upstream emissions from the provision of the weanlings that are fattened.',
  'IT-F.226': 'In IT F226 two scenarios are considered: the usage of algae as feed stuff and the conversion of the production system to pasture based fattening. The usage of algae as feed stuff starts at 320€/ton. The algae is used to replace concentrates and partially silage maize. By this profit and protein and calorie efficiency are improved while GHG emissions rise. Algae bares a higher carbon load then the replaced feed and leads to higher methane emissions of the animals as the ratio of protein and energy in the algae is less favorable for the animals. The effect is increased if the price of algae further drops.For the pasture scenario we assumed that 28ha are permanent grasslands. The idea is that cattle production should take place on land that cannot be directly used for primary food production. Like in the other case studies, we divide this innovation into two scenarios: one with low nutrient content of the grazed grass and one with high nutrient content. In both scenarios profit, protein efficiency and calorie efficiency are increased. The GWP worsens in both scenario. With a higher nutrient yield the increase in profit and calorie and protein efficiency increases further alongside with a lower increase in GWP. The farm is not able to utilize the whole area of grassland as pasture as it does not fit into the farms production program. Limitations arise in the herd management and nutrient cycling. Profits are rising as the efforts for fertilization, plant protection and diesel are reduced. Calorie and protein efficiency are improved as the arable produce is partially produced to grass that is not consumable by humans. In order to sustain the herd over the year, especially during the winter and summer, where grazing is not possible, the farm has to buy additional feedstuff. Furthermore, the farm uses the pasture to increase its herd as the pasture is more or less used as a feedlot with a high number of animals per ha. This leads to the increase in GWP compared to the baseline. The increase in GWP is comparably low and it is questionable, if the system is better organized and the pasture is fully utilized if it will occur. This could be subject of future research.',
  'IT-F.913': 'In ItF913 we analyse the usage of algae as feedstuff and the fattening of Holstein-cross bulls instead of the baseline beef breeds. Algae are adopted as feedstuff starting at a price of ~570€ per ton. All indicators are improved due to the replacement of concentrates in the ration. IF the price of algae is further decreased more concentrates are replaced. At a price lower than 200€ maize silage in the ration is replaced with algae leading to increased GHG emissions as maize silage has a lower carbon footprint compared to the chlorella algae. The fattening of Holstein cross proves to be more efficient in calorie and protein production and in terms of GHG emissions. However the price is 30% lower leading to a net loss of the enterprise if Holsteins are fattened instead of beef breeds, even without the consideration of upstream impacts from the production of the fattened weanlings. '
}